# Generated by Django 5.0.3 on 2024-04-02 04:54

from django.db import migrations

DEFAULT_TAGS = [
    ("fashion", "Fashion"),
    ("home decor", "Home Decor"),
    ("food & recipe", "Food & Recipe"),
    ("travel", "Travel"),
    ("art & design", "Art & Design"),
    ("photography", "Photography"),
    ("diy & craft", "DIY & Craft"),
    ("health & fitness", "Health & Fitness"),
    ("tech", "Tech"),
    ("books & literature", "Books & Literature"),
]

def populate_default_tags(apps, schema_editor):
    TagModel = apps.get_model("app", "Tag")
    for tag_value, _ in DEFAULT_TAGS:
        TagModel.objects.get_or_create(name=tag_value)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_default_tags),
    ]
