# Generated by Django 5.0.3 on 2024-04-03 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20240401_2354"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("fashion", "Fashion"),
                    ("home decor", "Home Decor"),
                    ("food & recipe", "Food & Recipe"),
                    ("travel", "Travel"),
                    ("art & design", "Art & Design"),
                    ("photography", "Photography"),
                    ("diy & craft", "DIY & Craft"),
                    ("health & fitness", "Health & Fitness"),
                    ("tech", "Tech"),
                    ("books & literature", "Books & Literature"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.card"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
